bed:
    unsorted_ascertainment     :
        bigsteffi: "/r1/people/public/AncientDNA/probe_designs/AA207-210_bigSteffi/bedfiles/chagyrskaya_update/array_archaics_AFR2_combined.bed"
        afrhigh: "/r1/people/public/AncientDNA/probe_designs/AA207-210_bigSteffi/bedfiles/chagyrskaya_update/array_AFR2_highfreq.bed"
        afrunif : "/r1/people/public/AncientDNA/probe_designs/AA207-210_bigSteffi/bedfiles/chagyrskaya_update/array_AFR2_unifreq.bed"
        nea: "/r1/people/public/AncientDNA/probe_designs/AA207-210_bigSteffi/bedfiles/chagyrskaya_update/array_archaics_combined.bed"
        neafixedderived: "/r1/people/public/AncientDNA/probe_designs/AA207-210_bigSteffi/bedfiles/chagyrskaya_update/array_archaic_fixed_derived.bed"
        neavar: "/r1/people/public/AncientDNA/probe_designs/AA207-210_bigSteffi/bedfiles/chagyrskaya_update/array_archaic_var.bed"
        fixdiff: "/r1/people/public/AncientDNA/probe_designs/AA207-210_bigSteffi/bedfiles/chagyrskaya_update/array_fixed_diff.bed"
        afr: "/r1/people/public/AncientDNA/probe_designs/AA207-210_bigSteffi/bedfiles/chagyrskaya_update/array_AFR2_combined.bed"
        twomillion : "/mnt/expressions/mateja/Early_modern_humans/Upper_Palaeolithic_project_Mateja/nuclear_captures/targets/2.2_million.snp.as.bed"
        archaicadmixture :  "/mnt/expressions/mateja/Early_modern_humans/Upper_Palaeolithic_project_Mateja/nuclear_captures/targets/Archaic.complete.sorted.snp.as.bed"
        thirdallele : "/mnt/sequencedb/PopGen/cesare/genomes/hg19_evan_third/modified_positions.bed.gz"

fa: "/mnt/solexa/Genomes/hg19_evan/whole_genome.fa"

vcf: 
    giantvcf: "/mnt/sequencedb/gendivdata/2_genotypes/giantVcfs/merged_var_nosing_sites_arch_apes_sgdp1_g1000_chr{CHROM}.vcf.gz"

filter: #filers are in pgdirect.gt.ReadGT.vcfgt
    _default:
        deam_only : False
        min_length : 32
        max_length : 1000
        minq : 25
        pos_in_read_cutoff: 3
    nofilter:
        minq : 25
    deam:
        deam_only : True
        deam_bases : 3
    l3570deam:
        min_length : 35
        max_length : 70
        deam_only : True
        deam_bases : 3

