sampleset:
    sgdpafr:   #grep Afri /mnt/sequencedb/gendivdata/2_genotypes/giantVcfs/sample_info.csv   | cut -f1 -d,
        - B_Dinka-3
        - B_Ju_hoan_North-4
        - B_Mandenka-3
        - B_Mbuti-4
        - B_Yoruba-3
        - S_BantuHerero-1
        - S_BantuHerero-2
        - S_BantuKenya-1
        - S_BantuKenya-2
        - S_BantuTswana-1
        - S_BantuTswana-2
        - S_Biaka-1
        - S_Biaka-2
        - S_Dinka-1
        - S_Dinka-2
        - S_Esan-1
        - S_Esan-2
        - S_Gambian-1
        - S_Gambian-2
        - S_Ju_hoan_North-1
        - S_Ju_hoan_North-2
        - S_Ju_hoan_North-3
        - S_Khomani_San-1
        - S_Khomani_San-2
        - S_Luhya-1
        - S_Luhya-2
        - S_Luo-1
        - S_Luo-2
        - S_Mandenka-1
        - S_Mandenka-2
        - S_Masai-1
        - S_Masai-2
        - S_Mbuti-1
        - S_Mbuti-2
        - S_Mbuti-3
        - S_Mende-1
        - S_Mende-2
#        - S_Mozabite-1
#        - S_Mozabite-2
#        - S_Saharawi-1
#        - S_Saharawi-2
        - S_Somali-1
        - S_Yoruba-1
        - S_Yoruba-2
    tinyvcf:
        - panTro4
        - S_Mbuti-1
        - S_Mbuti-2
        - S_Mbuti-3
        - S_Papuan-1
        - S_Papuan-2
        - S_Papuan-3
        - S_Papuan-4
        - S_Sardinian-1
        - S_Sardinian-2
        - S_Han-1
        - S_Han-2
        - S_Karitiana-1
        - S_Karitiana-2
        - S_French-1
        - S_French-2
        - B_French-3
    1000gafr:   #grep "[YL][RW][IK]" /mnt/sequencedb/gendivdata/2_genotypes/giantVcfs/sample_info.csv   | cut -f1 -d,
        - NA18486
        - NA18488
        - NA18489
        - NA18498
        - NA18499
        - NA18501
        - NA18502
        - NA18504
        - NA18505
        - NA18507
        - NA18508
        - NA18510
        - NA18511
        - NA18516
        - NA18517
        - NA18519
        - NA18520
        - NA18522
        - NA18523
        - NA18853
        - NA18856
        - NA18858
        - NA18861
        - NA18864
        - NA18865
        - NA18867
        - NA18868
        - NA18870
        - NA18871
        - NA18873
        - NA18874
        - NA18876
        - NA18877
        - NA18878
        - NA18879
        - NA18881
        - NA18907
        - NA18908
        - NA18909
        - NA18910
        - NA18912
        - NA18915
        - NA18916
        - NA18917
        - NA18923
        - NA18924
        - NA18933
        - NA18934
        - NA19017
        - NA19019
        - NA19020
        - NA19023
        - NA19024
        - NA19025
        - NA19026
        - NA19027
        - NA19028
        - NA19030
        - NA19031
        - NA19035
        - NA19036
        - NA19037
        - NA19038
        - NA19041
        - NA19042
        - NA19043
        - NA19092
        - NA19093
        - NA19095
        - NA19096
        - NA19098
        - NA19099
        - NA19102
        - NA19107
        - NA19108
        - NA19113
        - NA19114
        - NA19116
        - NA19117
        - NA19118
        - NA19119
        - NA19121
        - NA19129
        - NA19130
        - NA19131
        - NA19137
        - NA19138
        - NA19141
        - NA19143
        - NA19144
        - NA19146
        - NA19147
        - NA19149
        - NA19152
        - NA19153
        - NA19159
        - NA19160
        - NA19171
        - NA19172
        - NA19175
        - NA19184
        - NA19185
        - NA19189
        - NA19190
        - NA19197
        - NA19198
        - NA19200
        - NA19201
        - NA19204
        - NA19206
        - NA19207
        - NA19209
        - NA19210
        - NA19213
        - NA19214
        - NA19222
        - NA19223
        - NA19225
        - NA19235
        - NA19236
        - NA19238
        - NA19239
        - NA19247
        - NA19248
        - NA19256
        - NA19257
        - NA19307
        - NA19308
        - NA19309
        - NA19310
        - NA19312
        - NA19314
        - NA19315
        - NA19316
        - NA19317
        - NA19318
        - NA19319
        - NA19320
        - NA19321
        - NA19323
        - NA19324
        - NA19327
        - NA19328
        - NA19331
        - NA19332
        - NA19334
        - NA19338
        - NA19346
        - NA19347
        - NA19350
        - NA19351
        - NA19355
        - NA19360
        - NA19372
        - NA19374
        - NA19375
        - NA19376
        - NA19377
        - NA19378
        - NA19379
        - NA19380
        - NA19383
        - NA19384
        - NA19385
        - NA19390
        - NA19391
        - NA19393
        - NA19394
        - NA19395
        - NA19397
        - NA19399
        - NA19401
        - NA19403
        - NA19404
        - NA19428
        - NA19429
        - NA19430
        - NA19431
        - NA19434
        - NA19435
        - NA19436
        - NA19437
        - NA19438
        - NA19439
        - NA19440
        - NA19443
        - NA19445
        - NA19446
        - NA19448
        - NA19449
        - NA19451
        - NA19452
        - NA19454
        - NA19455
        - NA19456
        - NA19457
        - NA19461
        - NA19462
        - NA19463
        - NA19466
        - NA19467
        - NA19468
        - NA19471
        - NA19472
        - NA19473
        - NA19474
        - NA19475
    archhc:
        - AltaiNeandertal
        - Vindija33.19
        - Denisova
        - Ust_Ishim
        - Chagyrskaya-Phalanx
        - panTro4
    sgdpeur:
        - "B_Crete-1"
        - "B_Crete-2"
        - "B_French-3"
        - "B_Sardinian-3"
        - "S_Abkhasian-1"
        - "S_Abkhasian-2"
        - "S_Adygei-1"
        - "S_Adygei-2"
        - "S_Albanian-1"
        - "S_Armenian-1"
        - "S_Armenian-2"
        - "S_Basque-1"
        - "S_Basque-2"
        - "S_BedouinB-1"
        - "S_BedouinB-2"
        - "S_Bergamo-1"
        - "S_Bergamo-2"
        - "S_Bulgarian-1"
        - "S_Bulgarian-2"
        - "S_Chechen-1"
        - "S_Czech-2"
        - "S_Druze-1"
        - "S_Druze-2"
        - "S_English-1"
        - "S_English-2"
        - "S_Estonian-1"
        - "S_Estonian-2"
        - "S_Finnish-1"
        - "S_Finnish-2"
        - "S_Finnish-3"
        - "S_French-1"
        - "S_French-2"
        - "S_Georgian-1"
        - "S_Georgian-2"
        - "S_Greek-1"
        - "S_Greek-2"
        - "S_Hungarian-1"
        - "S_Hungarian-2"
        - "S_Icelandic-1"
        - "S_Icelandic-2"
        - "S_Iranian-1"
        - "S_Iranian-2"
        - "S_Iraqi_Jew-1"
        - "S_Iraqi_Jew-2"
        - "S_Jordanian-1"
        - "S_Jordanian-2"
        - "S_Jordanian-3"
        - "S_Lezgin-1"
        - "S_Lezgin-2"
        - "S_North_Ossetian-1"
        - "S_North_Ossetian-2"
        #- "S_Norwegian-1"
        - "S_Orcadian-1"
        - "S_Orcadian-2"
        - "S_Palestinian-1"
        - "S_Palestinian-2"
        - "S_Palestinian-3"
        - "S_Polish-1"
        - "S_Russian-1"
        - "S_Russian-2"
        - "S_Saami-1"
        - "S_Saami-2"
        - "S_Samaritan-1"
        - "S_Sardinian-1"
        - "S_Sardinian-2"
        - "S_Spanish-1"
        - "S_Spanish-2"
        - "S_Tajik-1"
        - "S_Tajik-2"
        - "S_Turkish-1"
        - "S_Turkish-2"
        - "S_Tuscan-1"
        - "S_Tuscan-2"
        - "S_Yemenite_Jew-1"
        - "S_Yemenite_Jew-2"
    sgdpeas:
        - "B_Dai-4"
        - "B_Han-3"
        - "S_Ami-1"
        - "S_Ami-2"
        - "S_Atayal-1"
        - "S_Burmese-1"
        - "S_Burmese-2"
        - "S_Cambodian-1"
        - "S_Cambodian-2"
        - "S_Dai-1"
        - "S_Dai-2"
        - "S_Dai-3"
        - "S_Daur-2"
        - "S_Han-1"
        - "S_Han-2"
        - "S_Hezhen-1"
        - "S_Hezhen-2"
        - "S_Japanese-1"
        - "S_Japanese-2"
        - "S_Japanese-3"
        - "S_Kinh-1"
        - "S_Kinh-2"
        - "S_Korean-1"
        - "S_Korean-2"
        - "S_Lahu-1"
        - "S_Lahu-2"
        - "S_Miao-1"
        - "S_Miao-2"
        - "S_Naxi-1"
        - "S_Naxi-2"
        - "S_Naxi-3"
        - "S_Oroqen-1"
        - "S_Oroqen-2"
        - "S_She-1"
        - "S_She-2"
        - "S_Thai-1"
        - "S_Thai-2"
        - "S_Tu-1"
        - "S_Tu-2"
        - "S_Tujia-1"
        - "S_Tujia-2"
        - "S_Uygur-1"
        - "S_Uygur-2"
        - "S_Xibo-1"
        - "S_Xibo-2"
        - "S_Yi-1"
        - "S_Yi-2"
