panels:
    oldmh :
        - Yana1
        - Yana2
        - Kostenki14sg
        - Salkhit
        - UstIshim
        - Sunghir1
        - Sunghir2
        - Sunghir3
        - Sunghir4
        - Tianyuan
        - Malta
        - Oase
        - Vestonice16
        - GoyetQ116-11
    oldcrappymh :
        - Muierii2
        - Paglicci133
        - Cioclovina1
        - Kostenki12
        - KremsWA3
        - Vestonice14
        - Pavlov1
        - Vestonice43
        - GoyetQ53-1
        - Paglicci108
        - Ostuni1
    othermh:
        - Mota
        - Kolyma
        - Loschbour
        - LBK
        - Anzick
        - Karelia_I0061
        - Latvia_HG1
        - Kennewick
        - Villabruna
        - Taforalt_011
        - Taforalt_013
        - Taforalt_014
        - DevilsGate1
        - DevilsGate2
        - AfontovaGora2
        - ElMiron
    crappymh:
        - AfontovaGora2
        - AfontovaGora3
        - Bockstein
        - Brillenhohle
        - Burkhardtshohle
        - Chaudardes1
        - Cioclovina1
        - Continenza
        - DevilsGate1
        - DevilsGate2
        - ElMiron
        - Falkenstein
        - GoyetQ116-11
        - GoyetQ2
        - GoyetQ376-19
        - GoyetQ53-1
        - GoyetQ56-16
        - HohleFels49
        - HohleFels79
        - Iboussieres39
        - Kennewick
        - Kolyma
        - Kostenki12
        - Kostenki14
        - Kostenki14sg
        - KremsWA3
        - LBK
        - LesCloseaux13
        - Loschbour
        - Malta
        - Mota
        - Muierii2
        - Oase
        - Ofnet
        - Ostuni1
        - Ostuni2
        - Paglicci108
        - Paglicci133
        - Pavlov1
        - Ranchot
        - Rochedane
        - Salkhit
        - Sunghir1
        - Sunghir2
        - Sunghir3
        - Sunghir4
        - Tianyuan
        - UstIshim
        - Vestonice13
        - Vestonice14
        - Vestonice15
        - Vestonice16
        - Vestonice43
        - Villabruna
        - Latvia_HG1
        - Ukraine_HG1
        - Taforalt_008
        - Taforalt_009
        - Taforalt_010
        - Taforalt_012
        - Taforalt_013
        - Taforalt_014
        - Taforalt_015
        - Taforalt_016
        - Yana1
        - Yana2
    nea :
        - Nadale1
        - Chagyrskaya02
        - Chagyrskaya07
        - Chagyrskaya09
        - Chagyrskaya12
        - Chagyrskaya13
        - Chagyrskaya17
        - Chagyrskaya19
        - Chagyrskaya41
        - Chagyrskaya60
        - GoyetQ561
        - aaGoyetQ573
        - aaGoyetQ572
        - aaGoyetQ3054
        - Stajnia
        - lescottes
        - mez2
        - mez1
        - hst
        - HohlensteinStadel
        - goyet
        - vindijag1
        - vindija3315
        - vindija3316
        - vindija3325
        - vindija3326
        - aaVindija1141
        - spy1
        - Spy1
        - Spy8
        - Denisova15
        - Okladnikov11
        - LaGuelga1
        - LaGuelga4
        - ArcysurCure
        - aaFeldhofer1
        - elsidron1253
        - forbes_quarry
        - altai
        - vindija3319
        - chagyrskaya08
        - sima
        - sima2
    crappynea :
        - devils_tower
        - Denisova9
        - Chagyrskaya1141
    aanea :
        - Denisova8
        - Denisova11
        - Denisova4
        - Denisova2
        - Chagyrskaya07
        - aaVindija1141
        - aaVindija87
        - aaGoyetQ561
        - aaGoyetQ571
        - aaGoyetQ572
        - aaGoyetQ573
        - aaGoyetQ571
        - aaGoyetQ3054
        - aaMez2
        - aaSpy94a
        - aaFeldhofer1
        - aaArcy
        - spy1
        - goyet
        - lescottes
        - mez2
        - vindijag1
        - sima
        - hst
        - scladina
        - mez1
        - vindija3315
        - vindija3316
        - vindija3325
        - vindija3326
        - elsidron1253
        - forbes_quarry
    denisova:
        - Denisova2
        - Denisova4
        - Denisova8
        - Denisova11
        - Denisova13
    presentday:
        - "SS6004467-dedup"
        - "SS6004468-dedup"
        - "SS6004469-dedup"
        - "SS6004470-dedup"
        - "SS6004471-dedup"
        - "SS6004472-dedup"
        - "SS6004473-dedup"
        - "SS6004474-dedup"
        - "SS6004475-dedup"
        - "SS6004476-dedup"
        - "SS6004477-dedup"
        - "SS6004478-dedup"
        - "SS6004479-dedup"
        - "SS6004480-dedup"
    highcovnea :
        - altai
        - vindija3319
        - chagyrskaya08
    mh :
        - Yana1
        - Yana2
        - Kostenki14sg
        - Salkhit
        - UstIshim
        - Sunghir1
        - Sunghir2
        - Sunghir3
        - Sunghir4
        - Tianyuan
        - Malta
        - Oase
        - Vestonice16
        - Mota
        - Kolyma
        - Loschbour
        - LBK
        - Anzick
        - Karelia_I0061
        - Latvia_HG1
        - Kennewick
        - Villabruna
        - Taforalt_011
        - Taforalt_013
        - Taforalt_014
        - DevilsGate1
        - DevilsGate2
        - AfontovaGora2
        - ElMiron
    mhsmall :
        - Kostenki14sg
        - UstIshim
        - Sunghir3
        - Sunghir4
        - Tianyuan
        - Malta
        - Oase
        - Vestonice16
        - Karelia_I0061
        - Villabruna
    mhtiny :
        - Kostenki14sg
        - UstIshim
        - Sunghir3
        - Sunghir4
        - Tianyuan
    d2 :
        - Denisova2
        - Denisova11
    nea2 :
        - Chagyrskaya07
        - lescottes
        - mez2
        - mez1
        - goyet
        - spy1
        - altai
        - vindija3319
        - chagyrskaya08
    mh3 :
        - Yana1
        - Kostenki14sg
        - Salkhit
        - UstIshim
        - Tianyuan
        - Malta
        - Oase
        - Mota
        - Kolyma
        - Loschbour
        - LBK
        - Anzick
        - ElMiron
        - GoyetQ116-11

    test : 
        - Denisova15
        - Chagyrskaya02
