region:
    test1:
        chrom: 1
        start: 223e6
        end: 231e6
    test2:
        chrom: 2
        start: 155e6
        end: 165e6
    testd1:
        chrom : 2
        start : 150e6
        end: 170e6
    testd2:
        chrom : 8
        start : 100e6
        end: 150e6
    testd3:
        chrom : 11
        start : 20e6
        end: 50e6
    testd4:
        chrom : 9
        start : 0e6
        end: 140e6
    testn1:
        chrom : 1
        start : 48e6
        end : 52e6
    chr18:
        chrom: 18
        start: 35e6
        end: 45e6


