[tool.poetry]
name = "admixfrog"
version = "0.0.0"
description = "Local Ancestry Inference for low-coverage ancient DNA data"
authors = ["benjamin_peter <benjamin_peter@eva.mpg.de>"]
license = "BSD"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8"
pandas = ">=1.5"
numba = ">=0.42"
numpy = ">=1.0"
scipy = ">=1.1"
pybedtools = ">=0.7.10"
pysam = ">=0.15.0"
pyyaml = ">=5.0"
cython = ">=0.29"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"


[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
bump = true
pattern  = "^(?P<base>\\d+\\.\\d+\\.\\d+)(-?((?P<stage>[a-zA-Z]+)\\.?(?P<revision>\\d+)?))?"


#format = "{{base}}"
#format-jinja = "{% if distance == 0 %}{{ base }}{% else %}{{ base }}+{{ distance }}.{{ commit }}{% endif %}"

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"
